version: '3.8'

services:
  db-auth:
    image: mysql:8.0
    container_name: db_hotel_auth
    restart: always
    environment:
      MYSQL_DATABASE: db_hotel_auth
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"