spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: reserva-route
              uri: lb://RESERVA
              predicates:
                - Path=/api/v1/reservas/**
              filters:
                - AddResponseHeader=X-Gateway, api-gateway

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}